package com.woorido.notification.domain;

public enum NotificationType {
    // 챌린지 관련
    CHALLENGE_JOINED, CHALLENGE_LEFT, CHALLENGE_ACTIVATED, CHALLENGE_CLOSED,
    
    // 서포트/납입 관련
    SUPPORT_REMINDER, SUPPORT_PAID, SUPPORT_OVERDUE,
    
    // 모임 관련
    MEETING_CREATED, MEETING_VOTE_STARTED, MEETING_CONFIRMED, MEETING_CANCELLED, MEETING_REMINDER,
    
    // 지출 관련
    EXPENSE_VOTE_STARTED, EXPENSE_APPROVED, EXPENSE_REJECTED, BARCODE_ISSUED,
    
    // 투표 관련
    VOTE_STARTED, VOTE_CLOSED, KICK_APPROVED, LEADER_KICKED,
    
    // SNS 관련
    POST_LIKED, POST_COMMENTED, COMMENT_LIKED, COMMENT_REPLIED,
    
    // 시스템 관련
    SYSTEM_NOTICE, ACCOUNT_CHARGED, ACCOUNT_WITHDRAWN, REPORT_RESULT
}
